name = "stemaa-web"
compatibility_date = "2024-12-01"
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "stemaa-contacts"
database_id = "363a10db-ca1e-45f5-b559-396b8f235a2a"
